allowed_actions:
- web_search
- image_search
- reverse_search
- geolocate
benchmark_kwargs:
  variant: dev
benchmark_name: gaza_israel
continue_experiment_dir: null
experiment_name: default
fact_checker_kwargs:
  decompose: false
  decontextualize: false
  filter_check_worthy: false
  interpret: false
  max_iterations: 3
  max_result_len: 64000
  procedure_variant: summary/dynamic
llm: gemini-2.0-flash-lite
llm_kwargs:
  temperature: 0.01
n_samples: null
n_workers: 2
print_log_level: info
random_sampling: false
sample_ids: null
tools_config:
  geolocator: null
  searcher:
    limit_per_search: 3
    search_engine_config:
      google: null
      google_vision: null
